[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "rsctl CLI（命令行入口）"

[[bin]]
name = "rsctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

include_dir = "0.7"

core = { path = "../core" }
utils = { path = "../utils" }

[build-dependencies]
# build.rs 用于跟踪 ../templates 变更，触发 include_dir! 重新编译


