[package]
name = "rust-zero"
version = "0.1.0"
edition = "2024"
description = "rust-zero 门面 crate：对外统一入口（re-export core/rest）"
license = "Apache-2.0"
repository = "https://github.com/fucktx/rust-zero"
readme = "../../README.md"

[features]
default = []
axum = ["rz_rest/axum"]
actix = ["rz_rest/actix"]
jwt = ["rz_rest/jwt"]

[dependencies]
rz_core = { package = "rz-core", path = "../rz-core" }
rz_rest = { package = "rz-rest", path = "../rz-rest", default-features = false }


