// Code scaffolded by rsctl. Safe to edit.
// rsctl {{.version}}

//! Generated by rsctl. Safe to edit.

use std::sync::Arc;

use anyhow::Context;
use rust_zero::conf;

mod config;
mod handler;
mod logic;
mod middleware;
mod svc;
mod types;

const DEFAULT_CONFIG_PATH: &str = "etc/{{.serviceName}}.yaml";

fn parse_config_path() -> String {
    let mut args = std::env::args().skip(1);
    let mut path = DEFAULT_CONFIG_PATH.to_string();

    while let Some(a) = args.next() {
        if a == "-f" || a == "--config" {
            if let Some(v) = args.next() {
                path = v;
            }
            continue;
        }
        if let Some(v) = a.strip_prefix("--config=") {
            path = v.to_string();
        }
    }

    path
}

{{.mainAttr}}
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let config_file = parse_config_path();

    let mut c = config::Config::default();
    conf::must_load(&config_file, &mut c);

    print_banner(&c);
    tracing::info!("Starting server at {}:{}...", c.rest.host, c.rest.port);

    let engine = rust_zero::rest::Engine::new(c.rest.clone());
    let svc_ctx = Arc::new(svc::ServiceContext::new(c));
    let app = register_handlers!(svc_ctx);
{{.serverStart}}

    Ok(())
}

fn print_banner(_c: &config::Config) {
    // TODO: 这里可以打印项目 banner / 版本信息等
}
