// Code generated by rsctl. DO NOT EDIT.
// rsctl {{.version}}

#[macro_export]
macro_rules! register_handlers {
    ($svc_ctx:expr) => {
        rust_zero::rest::router! {
            {{.routesAdditions}}
        }
    };
}
