// placeholder (axum) - reuse `templates/api/rs/types.tpl`

// Code generated by rsctl. DO NOT EDIT.
// rsctl {{.version}}

use serde::{Deserialize, Serialize};

{{if .containsTime}}
use chrono::{DateTime, Utc};
{{end}}

{{.types}}


